spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/projectdb
spring.datasource.username=projectuser
spring.datasource.password=projectpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true